### ISSUE TITLE
Use snippet names without prefix

### ISSUE THREAD

**Issue by guerrero** [danielbayley/atom-modular-snippets#5]
I don't know if there's a good reason for use a prefix before each snippet name but the problem is that it produces that the name can't be read in the snippet panel:

![atom-modular-snippets-screenshot](https://cloud.githubusercontent.com/assets/3751801/20037870/5af88ad0-a429-11e6-8dc5-c7f120bee9ee.png)

IMHO, if there's no reason about to use the prefix it would be helpful to use only the name.

**Comment by danielbayley** [comment]
> I don't know if there's a good reason for use a prefix before each snippet name

@guerrero The reason for prefixing the file path to the snippet name was to allow snippets to have the same name across files without overriding each other. When you're using a single file you can keep track of that, but once you break your snippets up into multiple files and subfolders (_and_ even across projects) as this package allows, it would be much harder to notice random snippets disappearing due to a name clash, so there needs to be some kind of unique ID.

However, I just released an update which fixes this using [`rightLabelHTML`](https://github.com/atom/snippets#optional-parameters).

**Comment by guerrero** [comment]
Great! Thanks for the detailed explanation and for the update :)
